__all__ = [
    "Constant"
]
class Constant:
    BOTTOM_LEFT_IMG_KEY = "bottomleftimgkey"
    BOTTOM_RIGHT_IMG_KEY = "bottomrightimgkey"
    CENTER_DRAWER_NAME="centerdrawername"
    LEFT_CONTAINER_VISIBILITY="leftcontainervisibility"
    RIGHT_CONTAINER_VISIBILITY="rightcontainervisibility"
    CENTER_CONTAINER_VISIBILITY="centercontainervisibility"
    BOTTOM_CONTAINER_VISIBILITY="bottomcontainervisibility"
    CENTER_DRAWER_VISIBILITY="centerdrawervisibility"
    CENTER_ACTIVE_UI="centeractiveui"
    CENTER_RESULT_OPACITY="centerresultopacity"
    CENTER_PLANE_OPACITY="centerplaneopacity"
    CENTER_RESULT_REPRESENTATION="centerresultrepresentation"
    CENTER_PLANE_REPRESENTATION="centerplanerepresentation"
    CENTER_RESULT_COLOR_ARRAY_IDX="centerresultcolorarrayidx"
    CENTER_PLANE_COLOR_ARRAY_IDX="centerplanecolorarrayidx"
    CENTER_RESULT_COLOR_PRESET="centerresultcolorpreset"
    CENTER_PLANE_COLOR_PRESET="centerplanecolorpreset"
    CENTER_PLANE_TYPE="centerplanetype"
    CENTER_PLANE_X_VALUE="centerplanexvalue"
    CENTER_PLANE_Y_VALUE="centerplaneyvalue"
    CENTER_PLANE_Z_VALUE="centerplanezvalue"
    CENTER_ENABLE_PICKING="centerenablepicking"
    CENTER_PICKING_DATA="centerpickdata"
    CENTRE_TOOL_TIP="centertooltip"
    CENTER_TOOL_TIP_STYLE="centertooltipstyle"
    CENTER_PIXEL_RATIO="centerpixelratio"
